<a href="https://colab.research.google.com/github/Danendra10/Learning-Neural-Networks/blob/main/PyTorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.autograd as autog

In [13]:
data_x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
data_y = np.array([[0, 0, 0, 1]]).T
data_x = autog.Variable(torch.FloatTensor(data_x))
data_y = autog.Variable(torch.FloatTensor(data_y), requires_grad=False)

in_dim = 2
out_dim = 1
epochs = 15000
epoch_print = epochs / 5
l_rate = 0.001

In [34]:

class NeuralNet(nn.Module):
    def __init__(self, input_size, output_size):
        super(NeuralNet, self).__init__()
        self.layer1 = nn.Linear(input_size, 6)
        self.inter = nn.Linear(6, 6)
        self.logsig = nn.LogSigmoid()
        self.layer2 = nn.Linear(6, output_size)


    def forward(self, x):
        # You may want to use torch.nn.functional.sigmoid activation
        x = self.layer1(x)
        x = self.logsig(x)
        x = self.inter(x)
        x = self.inter(x)
        x = self.inter(x)
        x = self.inter(x)
        x = self.layer2(x)
        return x



In [35]:
model = NeuralNet(in_dim, out_dim)
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=l_rate)



In [36]:
for epoch in range(epochs):
    optimizer.zero_grad()
    pred = model(data_x)
    loss = criterion(pred, data_y)
    loss.backward()
    optimizer.step()
    if (epoch + 1) % epoch_print == 0:
        print("Epoch %d  Loss %f" %(epoch + 1, loss.item()))

Epoch 3000  Loss 0.000012
Epoch 6000  Loss 0.000001
Epoch 9000  Loss 0.000000
Epoch 12000  Loss 0.000000
Epoch 15000  Loss 0.000000


In [32]:
for x, y in zip(data_x, data_y):
    pred = model(x)
    # See int(pred > 0), that's the only change
    print("Input", list(map(int, x)), "Pred", int(pred > 0), "Output", int(y))


Input [0, 0] Pred 0 Output 0
Input [0, 1] Pred 0 Output 0
Input [1, 0] Pred 0 Output 0
Input [1, 1] Pred 1 Output 1


In [33]:
for layer in model.children():
    if isinstance(layer, nn.Linear):
        print(layer.state_dict()['weight'])
        print(layer.state_dict()['bias'])

tensor([[-1.2211,  3.4053],
        [-1.4559,  3.5618],
        [-4.2792, -3.0867],
        [-2.6666, -3.2171],
        [ 3.8357, -1.6571],
        [ 3.1326, -0.8114]])
tensor([-2.4591, -2.4458,  2.9049,  1.9091, -2.4885, -2.6294])
tensor([[ 2.2481,  2.3403, -3.0034, -2.0605,  2.1918,  1.9996]])
tensor([-1.2701])
